In [1]:
import torch

In [3]:
a = torch.FloatTensor([[0.8, 0.7, 0.2],
                      [1, 0.5, 0.4],
                      [0.49, 0.1, 0]])
a.apply_(lambda x: int(x >= 0.5)).to(torch.long)

tensor([[1, 1, 0],
        [1, 1, 0],
        [0, 0, 0]])

In [10]:
a = torch.LongTensor([[[1, 1, 0],
                      [1, 1, 0],
                      [0, 0, 0]]])

b = torch.LongTensor([[[0, 0, 0],
                      [0, 1, 1],
                      [0, 1, 1]]])

In [13]:
a.shape

torch.Size([1, 3, 3])

In [14]:
a & b

tensor([[[0, 0, 0],
         [0, 1, 0],
         [0, 0, 0]]])

In [15]:
a | b

tensor([[[1, 1, 0],
         [1, 1, 1],
         [0, 1, 1]]])

In [16]:
torch.sum(a & b).item()

1

In [17]:
torch.sum(a | b).item()

7

In [2]:
from torchvision.models.segmentation import deeplabv3_resnet50

In [ ]:
model = deeplabv3_resnet50()

Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to C:\Users\jaaj/.cache\torch\hub\checkpoints\resnet50-0676ba61.pth


  0%|          | 0.00/97.8M [00:00<?, ?B/s]

In [4]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [10]:
a = a[..., None]
a.shape

(2, 3, 1)

In [12]:
b = np.concatenate((a, a, a), axis=-1)

In [13]:
b.shape

(2, 3, 3)

In [14]:
b

array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]]])